# Generated by Django 5.0.14 on 2026-05-15 12:38

import config.crypto
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_add_voice_preset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfig',
            name='api_key',
            field=config.crypto.EncryptedCharField(max_length=512),
        ),
    ]
